### ISSUE TITLE
.... combine forces?

### ISSUE THREAD

**Issue by jsonberry** [kievsash/rxjs-toolbox#1]
Hey @kievsash! Just noticed this got opened.. 

I started https://github.com/jsonberry/rxjs-toolkit which seems to have a similar approach. If you'd like, we can combine forces and get some of this into the same project.

Let me know what you think! 🙏

**Comment by kievsash** [comment]
Hey, Json!
I think it is possible, so lets chat in twitter

**Comment by kievsash** [comment]
https://stackoverflow.com/a/61377922

**Comment by jsonberry** [comment]
Sorry I didn't follow through here haha... life got busy and different :) 

Will just close this out <3
